### ISSUE TITLE
a fun one

### ISSUE THREAD

**Issue by knope** [m0r13/mclogalyzer#19]
###### this script is one of the coolest things since dynmap... please help.  :)

  (i'm curious what's changed since 7-12-2015.. for some reason it's been choking ever since.)

   (not sure if I'm hitting some issue with what ever the server is applying to the logs... I can provide all of my server logs for testing against if it will help.  I even tried removing the logs for 7-13 to see if it would help, to no avail.)

```
Parsing log 2015-05-20-1.log.gz (2015-05-20) ...
Parsing log 2015-05-20-2.log.gz (2015-05-20) ...
Parsing log 2015-05-21-1.log.gz (2015-05-21) ...
Parsing log 2015-05-21-2.log.gz (2015-05-21) ...
Parsing log 2015-05-21-3.log.gz (2015-05-21) ...
Parsing log 2015-05-22-1.log.gz (2015-05-22) ...
Parsing log 2015-05-23-1.log.gz (2015-05-23) ...
Parsing log 2015-05-23-2.log.gz (2015-05-23) ...
Parsing log 2015-05-23-3.log.gz (2015-05-23) ...
Parsing log 2015-05-24-1.log.gz (2015-05-24) ...
Parsing log 2015-05-24-2.log.gz (2015-05-24) ...
Parsing log 2015-05-24-3.log.gz (2015-05-24) ...
Parsing log 2015-05-24-4.log.gz (2015-05-24) ...
Parsing log 2015-05-24-5.log.gz (2015-05-24) ...
Parsing log 2015-05-25-1.log.gz (2015-05-25) ...
Parsing log 2015-05-26-1.log.gz (2015-05-26) ...
Parsing log 2015-05-27-1.log.gz (2015-05-27) ...
Parsing log 2015-05-28-1.log.gz (2015-05-28) ...
Parsing log 2015-05-28-2.log.gz (2015-05-28) ...
Parsing log 2015-05-28-3.log.gz (2015-05-28) ...
Parsing log 2015-05-29-1.log.gz (2015-05-29) ...Parsing log 2015-05-29-2.log.gz (2015-05-29) ...
Parsing log 2015-05-30-1.log.gz (2015-05-30) ...
Parsing log 2015-05-31-1.log.gz (2015-05-31) ...
Parsing log 2015-06-01-1.log.gz (2015-06-01) ...
Parsing log 2015-06-01-2.log.gz (2015-06-01) ...
Parsing log 2015-06-01-3.log.gz (2015-06-01) ...
Parsing log 2015-06-01-4.log.gz (2015-06-01) ...
Parsing log 2015-06-02-1.log.gz (2015-06-02) ...
Parsing log 2015-06-03-1.log.gz (2015-06-03) ...
Parsing log 2015-06-04-1.log.gz (2015-06-04) ...
Parsing log 2015-06-05-1.log.gz (2015-06-05) ...
Parsing log 2015-06-06-1.log.gz (2015-06-06) ...
Parsing log 2015-06-11-1.log.gz (2015-06-11) ...
Parsing log 2015-06-11-2.log.gz (2015-06-11) ...
Parsing log 2015-06-12-1.log.gz (2015-06-12) ...
Parsing log 2015-06-12-2.log.gz (2015-06-12) ...
Parsing log 2015-06-12-3.log.gz (2015-06-12) ...
Parsing log 2015-06-13-1.log.gz (2015-06-13) ...
Parsing log 2015-06-14-1.log.gz (2015-06-14) ...
Parsing log 2015-06-15-1.log.gz (2015-06-15) ...
Parsing log 2015-06-15-2.log.gz (2015-06-15) ...
Parsing log 2015-06-16-1.log.gz (2015-06-16) ...
Parsing log 2015-06-16-2.log.gz (2015-06-16) ...
Parsing log 2015-06-16-3.log.gz (2015-06-16) ...
Parsing log 2015-06-16-4.log.gz (2015-06-16) ...
Parsing log 2015-06-16-5.log.gz (2015-06-16) ...
Parsing log 2015-06-16-6.log.gz (2015-06-16) ...
Parsing log 2015-06-16-7.log.gz (2015-06-16) ...
Parsing log 2015-06-17-1.log.gz (2015-06-17) ...
Parsing log 2015-06-18-1.log.gz (2015-06-18) ...
Parsing log 2015-06-18-2.log.gz (2015-06-18) ...
Parsing log 2015-06-19-1.log.gz (2015-06-19) ...
Parsing log 2015-06-19-2.log.gz (2015-06-19) ...
Parsing log 2015-06-19-3.log.gz (2015-06-19) ...
Parsing log 2015-06-19-4.log.gz (2015-06-19) ...
Parsing log 2015-06-19-5.log.gz (2015-06-19) ...
Parsing log 2015-06-19-6.log.gz (2015-06-19) ...
Parsing log 2015-06-20-1.log.gz (2015-06-20) ...
Parsing log 2015-06-20-2.log.gz (2015-06-20) ...
Parsing log 2015-06-21-1.log.gz (2015-06-21) ...
Parsing log 2015-06-21-2.log.gz (2015-06-21) ...
Parsing log 2015-06-21-3.log.gz (2015-06-21) ...
Parsing log 2015-06-21-4.log.gz (2015-06-21) ...
Parsing log 2015-06-21-5.log.gz (2015-06-21) ...
Parsing log 2015-06-21-6.log.gz (2015-06-21) ...
Parsing log 2015-06-22-1.log.gz (2015-06-22) ...
Parsing log 2015-06-23-1.log.gz (2015-06-23) ...
Parsing log 2015-06-23-2.log.gz (2015-06-23) ...
Parsing log 2015-06-24-1.log.gz (2015-06-24) ...
Parsing log 2015-06-25-1.log.gz (2015-06-25) ...
Parsing log 2015-06-26-1.log.gz (2015-06-26) ...
Parsing log 2015-06-27-1.log.gz (2015-06-27) ...
Parsing log 2015-06-30-1.log.gz (2015-06-30) ...
Parsing log 2015-06-30-2.log.gz (2015-06-30) ...
Parsing log 2015-06-30-3.log.gz (2015-06-30) ...
Parsing log 2015-06-30-4.log.gz (2015-06-30) ...
Parsing log 2015-07-02-1.log.gz (2015-07-02) ...
Parsing log 2015-07-02-2.log.gz (2015-07-02) ...
Parsing log 2015-07-02-3.log.gz (2015-07-02) ...
Parsing log 2015-07-02-4.log.gz (2015-07-02) ...
Parsing log 2015-07-02-5.log.gz (2015-07-02) ...
Parsing log 2015-07-02-6.log.gz (2015-07-02) ...
Parsing log 2015-07-05-1.log.gz (2015-07-05) ...
Parsing log 2015-07-05-2.log.gz (2015-07-05) ...
Parsing log 2015-07-06-1.log.gz (2015-07-06) ...
Parsing log 2015-07-07-1.log.gz (2015-07-07) ...
Parsing log 2015-07-08-1.log.gz (2015-07-08) ...
Parsing log 2015-07-09-1.log.gz (2015-07-09) ...
Parsing log 2015-07-09-2.log.gz (2015-07-09) ...
Parsing log 2015-07-09-3.log.gz (2015-07-09) ...
Parsing log 2015-07-09-4.log.gz (2015-07-09) ...
Parsing log 2015-07-09-5.log.gz (2015-07-09) ...
Parsing log 2015-07-09-6.log.gz (2015-07-09) ...
Parsing log 2015-07-10-1.log.gz (2015-07-10) ...
Parsing log 2015-07-11-1.log.gz (2015-07-11) ...
Parsing log 2015-07-12-1.log.gz (2015-07-12) ...
Parsing log 2015-07-12-2.log.gz (2015-07-12) ...
```

the error is described below:

```
Traceback (most recent call last):
  File "/opt/scarcityfree/mclogalyzer/mclogalyzer/mclogalyzer.py", line 563, in <module>
    main()
  File "/opt/scarcityfree/mclogalyzer/mclogalyzer/mclogalyzer.py", line 535, in main
    users, server, chats = parse_logs(args["logdir"], since, whitelist_users)
  File "/opt/scarcityfree/mclogalyzer/mclogalyzer/mclogalyzer.py", line 380, in parse_logs
    for line in logfile:
  File "/usr/lib/python2.7/gzip.py", line 455, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 308, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xc1488c0b != 0x8753f9f8L
```

**Comment by knope** [comment]
this is fixed by #28 ... pending chance to test on running mc server  :D thanks @rk295
