### ISSUE TITLE
'ascii' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by Morketh** [m0r13/mclogalyzer#27]
Minecraft 1.7.10 with Forge 10.13.4.1566

This could be a possible duplicate of #26 or possibly #21 
```
Traceback (most recent call last):
  File "/usr/local/bin/mclogalyzer", line 7, in <module>
    mclogalyzer.main()
  File "/usr/local/lib/python2.7/dist-packages/mclogalyzer/mclogalyzer.py", line 565, in main
    last_update=time.strftime("%Y-%m-%d %H:%M:%S")))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/mclogalyzer/template.html", line 322, in top-level template code
    <li>{{ a }}</li>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```
If you need the server logs in question let me know. Also i attempted to run this on the screen console.log produced with the ```screen -L``` command apparently it didn't recognize that as a valid log file. As it ran the program with out error the stats page it produced was empty.

**Comment by rk295** [comment]
Hey @Morketh if you are still interested, I've fix this in #28
